package raysproject;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
public class AdmissionDetails extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    String str,url,cdata="";
    PreparedStatement stmt;
    int adm_no,year;
    Label l;
    DefaultTableModel model;
    boolean chk=true,flg=true;
    byte ctr=0;
    public AdmissionDetails() throws SQLException {
        initComponents();
          Image icon=Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/icon/repl_logo_(1)-small.png"));
        this.setIconImage(icon);
        con=ConnDb.conLink();
        setTitle("Admission Entry And Service Form");
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(submit_bt);
        doa_date.setDate(new java.sql.Date(System.currentTimeMillis()));
        regno_tf.requestFocus();
        //autogenerate admission form no
        stmt=con.prepareStatement("select adm_no from automatic");
        rs=stmt.executeQuery();
        rs.next();
        adm_no=rs.getInt(1)+1;
        Calendar cal=Calendar.getInstance();
        year = (cal.get(Calendar.YEAR))%100;
        stmt=con.prepareStatement("select max(ADM_NO) from ADMISSION");
        rs=stmt.executeQuery();
        if(rs.next()){
            String a=rs.getString(1);
            if(a!=null && year>(Integer.parseInt(a.substring(0, 2))))
                 adm_no=1;}
        autogen();
//        tab_pan.setVisible(false);
        url="select * from admission where reg_no=?";
        stmt=con.prepareStatement("select cname from course");
        rs=stmt.executeQuery();
        while(rs.next())
        {
            cou_box.addItem(rs.getString(1).toUpperCase());
            cdata=cdata+rs.getString(1).toUpperCase()+",";
        }
        ser_bx.setSelectedIndex(0);
    }
    public void autogen(){
        boolean auto=true;
        char ch=65;
        if(adm_no<10)
           str=""+year+ch+"00"+adm_no;
        else if(adm_no<100)
           str=""+year+ch+"0"+adm_no;
        else if(adm_no<1000){
           str=""+year+ch+adm_no;
        }
        else{
           JOptionPane.showMessageDialog(null,"More than 999 student not allowed");
           auto=false;
        }
        if(auto){
             formno_tf.setText(str); 
         }  
        else{
           submit_bt.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        formno1 = new javax.swing.JLabel();
        formno_tf = new javax.swing.JTextField();
        doa1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sname1 = new javax.swing.JLabel();
        sname_tf = new javax.swing.JTextField();
        regno1 = new javax.swing.JLabel();
        regno_tf = new javax.swing.JTextField();
        submit_bt = new javax.swing.JButton();
        reset_bt = new javax.swing.JButton();
        crstudied1 = new javax.swing.JLabel();
        prev_tf = new javax.swing.JTextField();
        crapplying1 = new javax.swing.JLabel();
        cou_box = new javax.swing.JComboBox<>();
        cou_tf = new javax.swing.JTextField();
        crfee1 = new javax.swing.JLabel();
        coufee_tf = new javax.swing.JTextField();
        disc1 = new javax.swing.JLabel();
        disc_tf = new javax.swing.JTextField();
        totfee1 = new javax.swing.JLabel();
        tot_fee = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        doa_date = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        ser_bx = new javax.swing.JComboBox<>();
        search_bt = new javax.swing.JButton();
        ser_tf = new org.jdesktop.swingx.JXSearchField();
        ref_bt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tab_pan = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        up_bt = new javax.swing.JButton();
        del_bt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        kGradientPanel2.setkEndColor(new java.awt.Color(102, 255, 102));
        kGradientPanel2.setkGradientFocus(800);
        kGradientPanel2.setkStartColor(new java.awt.Color(153, 255, 153));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMISSION FORM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(381, 381, 381))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formno1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        formno1.setText("Form Number");

        formno_tf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        formno_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formno_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formno_tfActionPerformed(evt);
            }
        });

        doa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doa1.setText("Date Of Admission");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sname1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sname1.setText("Student Name");
        jPanel4.add(sname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        sname_tf.setEditable(false);
        sname_tf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sname_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(sname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 227, 24));

        regno1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regno1.setText("Registration Number");
        jPanel4.add(regno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        regno_tf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        regno_tf.setAutoscrolls(false);
        regno_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regno_tf.setName(""); // NOI18N
        regno_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regno_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regno_tfFocusLost(evt);
            }
        });
        regno_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                regno_tfKeyTyped(evt);
            }
        });
        jPanel4.add(regno_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 227, 24));

        submit_bt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submit_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SUBMIT (1).png"))); // NOI18N
        submit_bt.setText("SUBMIT");
        submit_bt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        submit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btActionPerformed(evt);
            }
        });
        jPanel4.add(submit_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 120, 35));

        reset_bt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/resetpng (1).png"))); // NOI18N
        reset_bt.setText("RESET");
        reset_bt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        reset_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btActionPerformed(evt);
            }
        });
        reset_bt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reset_btKeyPressed(evt);
            }
        });
        jPanel4.add(reset_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 120, 35));

        crstudied1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        crstudied1.setText("Previous Course");
        jPanel4.add(crstudied1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        prev_tf.setEditable(false);
        prev_tf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prev_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(prev_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 227, 24));

        crapplying1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        crapplying1.setText("Course Applying");
        jPanel4.add(crapplying1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        cou_box.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cou_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Any Course" }));
        cou_box.setAutoscrolls(true);
        cou_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cou_boxActionPerformed(evt);
            }
        });
        jPanel4.add(cou_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 227, 30));

        cou_tf.setEditable(false);
        cou_tf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cou_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(cou_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 227, 24));

        crfee1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        crfee1.setText("Course Fee");
        jPanel4.add(crfee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        coufee_tf.setEditable(false);
        coufee_tf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coufee_tf.setText("0");
        coufee_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(coufee_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 227, 24));

        disc1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        disc1.setText("Discount ");
        jPanel4.add(disc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        disc_tf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        disc_tf.setText("0");
        disc_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        disc_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                disc_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                disc_tfFocusLost(evt);
            }
        });
        disc_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                disc_tfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                disc_tfKeyTyped(evt);
            }
        });
        jPanel4.add(disc_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 227, 24));

        totfee1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totfee1.setText("Total Fee");
        jPanel4.add(totfee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        tot_fee.setEditable(false);
        tot_fee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tot_fee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(tot_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 227, 24));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 862, 10));

        doa_date.setAutoscrolls(true);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(formno1)
                .addGap(18, 18, 18)
                .addComponent(formno_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(doa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doa_date, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doa_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formno1)
                        .addComponent(formno_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(doa1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Admission Entry Form", kGradientPanel2);

        jPanel6.setBackground(new java.awt.Color(38, 110, 115));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ser_bx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ser_bx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registration Number", "Student Name" }));
        ser_bx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ser_bxActionPerformed(evt);
            }
        });

        search_bt.setBackground(new java.awt.Color(0, 0, 204));
        search_bt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search_bt.setForeground(new java.awt.Color(255, 255, 255));
        search_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon-png-9964 (1).png"))); // NOI18N
        search_bt.setText("SEARCH");
        search_bt.setBorder(null);
        search_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btActionPerformed(evt);
            }
        });

        ser_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ser_tfKeyTyped(evt);
            }
        });

        ref_bt.setBackground(new java.awt.Color(255, 51, 51));
        ref_bt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ref_bt.setForeground(new java.awt.Color(255, 255, 255));
        ref_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh (1).png"))); // NOI18N
        ref_bt.setText("REFRESH");
        ref_bt.setBorder(null);
        ref_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ref_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adm_No", "Adm_Date", "Reg_No", "Cou_Apply", "Fee", "Discount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        tab_pan.setViewportView(table);

        up_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update (1).png"))); // NOI18N
        up_bt.setText("UPDATE");
        up_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_btActionPerformed(evt);
            }
        });

        del_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete (1).png"))); // NOI18N
        del_bt.setText("DELETE");
        del_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(tab_pan, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(894, 894, 894))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ser_bx, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ser_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(up_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_bt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(del_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ref_bt, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ser_bx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ref_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ser_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(up_bt, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(del_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab_pan, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 53, 891, 424));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADMISSION SERVICE FORM");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 51, 51)));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 12, -1, -1));

        jTabbedPane1.addTab("Admission Service Form", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formno_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formno_tfActionPerformed
    }//GEN-LAST:event_formno_tfActionPerformed

    private void regno_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regno_tfFocusGained
        fgcheck(regno_tf);
    }//GEN-LAST:event_regno_tfFocusGained

    private void regno_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regno_tfFocusLost

        flcheck(regno_tf);
        if(regno_tf.getText().length()!=0){
            try {
                stmt=con.prepareStatement("select sname from registration where reg_no=?");
                stmt.setString(1, regno_tf.getText().toUpperCase());
                rs=stmt.executeQuery();
                if(rs.next())
                    sname_tf.setText(rs.getString(1));
                 stmt=con.prepareStatement("select distinct cou_apply from admission where reg_no=?");
                stmt.setString(1, regno_tf.getText().toUpperCase());
                rs=stmt.executeQuery();
                String str="";
                while(rs.next())
                    str=str+rs.getString(1)+",";
                ArrayList <String> x=new ArrayList<>();
                for(String a:str.split(","))
                {
                    if(!x.contains(a))
                         x.add(a);
                }    
                prev_tf.setText(x.toString().substring(1,x.toString().length()-1));
                if(prev_tf.getText().length()==0)
                    prev_tf.setText("None");
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_regno_tfFocusLost

    private void regno_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regno_tfKeyTyped
        char ch=evt.getKeyChar();
        if(evt.getKeyChar()==0&& regno_tf.getCaretPosition()==0||evt.getKeyChar()=='/' && regno_tf.getCaretPosition()==0)
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        else if(!(ch>=65 && ch<=90||ch>=97 && ch<=122||ch>=48 && ch<=57||ch=='/'))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_regno_tfKeyTyped

    private void submit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btActionPerformed
        if(regno_tf.getText().equals("*Field is Mandatory")||disc_tf.getText().equals("*Field is Mandatory")||cou_tf.getText().length()==0)
            chk=false;
        else if(regno_tf.getText().isEmpty()||disc_tf.getText().isEmpty())
            chk=false;
        else
            chk=true;
        check();
        if(chk){
            try {
                stmt=con.prepareStatement("insert into admission values(?,?,?,?,?,?)");
                stmt.setString(1, formno_tf.getText());
                Calendar c=doa_date.getCalendar();
                String dt=""+c.get(Calendar.DATE)+"-"+(c.get(Calendar.MONTH)+1)+"-"+c.get(Calendar.YEAR);
                stmt.setString(2, dt);
                stmt.setString(3, regno_tf.getText().toUpperCase());
                String str=cou_tf.getText();
                str=str.substring(0, str.length()-1);
                stmt.setString(4, str.toUpperCase());
                stmt.setString(5, coufee_tf.getText());
                stmt.setString(6, disc_tf.getText());
                stmt.executeUpdate();
                adm_no=adm_no+1;
                JOptionPane.showMessageDialog(this, "Records inserted successfully!");
                submit_bt.setEnabled(false);
                 backdata.backup("admission");
                 backdata.backup("automatic");
//                 autobackup();
                    stmt=con.prepareStatement("update automatic set  adm_no=?");
                    stmt.setInt(1, adm_no-1);
                    stmt.executeUpdate();            
                String data[]={formno_tf.getText(),dt,regno_tf.getText(),prev_tf.getText(),sname_tf.getText(),str,coufee_tf.getText(),disc_tf.getText(),tot_fee.getText()};
                    new AdmissionInvoice(data).setVisible(true);
              autogen();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Something wrong in Submit Button!");
            } catch (WriteException ex) {
                Logger.getLogger(AdmissionDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "All Field is mandatory!");
        }
    }//GEN-LAST:event_submit_btActionPerformed

    private void reset_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btActionPerformed
        cou_box.removeAllItems();
        for(String a:cdata.split(","))
            cou_box.addItem(a);
        reset();
    }//GEN-LAST:event_reset_btActionPerformed

    private void reset_btKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reset_btKeyPressed
        char ch=evt.getKeyChar();
        if(ch==10)
        reset();
    }//GEN-LAST:event_reset_btKeyPressed

    private void cou_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cou_boxActionPerformed
        if(cou_box.getSelectedIndex()==-1)
            cou_box.addItem("Select Any Course");
        String st=cou_tf.getText();
        int a=Integer.parseInt(coufee_tf.getText());

        if(cou_box.getSelectedIndex()==0){
            cou_box.setBorder(new LineBorder(Color.RED));
        }
        else{
            
            try {
                stmt=con.prepareStatement("select cfee from course where upper(cname)=?");
                stmt.setString(1, cou_box.getSelectedItem().toString());
                rs=stmt.executeQuery();
                if(rs.next())
                    coufee_tf.setText(String.valueOf(a+rs.getInt(1)));
                else
                    System.out.println("Error in Course Box Selection!");
                tot_fee.setText(coufee_tf.getText());
            } catch (SQLException ex) {
            Logger.getLogger(AdmissionDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            cou_tf.setText(st+cou_box.getSelectedItem()+",");
            cou_box.removeItemAt(cou_box.getSelectedIndex());
        }
    }//GEN-LAST:event_cou_boxActionPerformed

    private void disc_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_disc_tfFocusGained
        fgcheck(disc_tf);
    }//GEN-LAST:event_disc_tfFocusGained

    private void disc_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_disc_tfFocusLost
        flcheck(disc_tf);      
    }//GEN-LAST:event_disc_tfFocusLost

    private void disc_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disc_tfKeyTyped
        char ch=evt.getKeyChar();
        if(evt.getKeyChar()=='%'||evt.getKeyChar()=='.' && disc_tf.getCaretPosition()==0)
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        else if(!(ch>=48 && ch<=57||ch=='%'||ch==46 && ctr==0||ch==8))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            if(ch==46 && ctr==0)
                ctr=1;
        }
    }//GEN-LAST:event_disc_tfKeyTyped

    private void search_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btActionPerformed
        if(ser_tf.getText().length()==0)
            JOptionPane.showMessageDialog(this, "SearchField is Empty!");
        else
            try {
                stmt=con.prepareStatement(url);
                stmt.setString(1, ser_tf.getText().toUpperCase());
                rs=stmt.executeQuery();
                model=(DefaultTableModel) table.getModel();
                model.setRowCount(0);
                while(rs.next()){
                    table.setVisible(true);
                    model.addRow(new Object []{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),false});
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(AdmissionDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_search_btActionPerformed

    private void ref_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ref_btActionPerformed
       table.setVisible(false);
    }//GEN-LAST:event_ref_btActionPerformed

    private void ser_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ser_tfKeyTyped
        if(ser_bx.getSelectedItem().equals("Registration Number"))
        {
            char ch=evt.getKeyChar();
            if(evt.getKeyChar()=='0' && ser_tf.getCaretPosition()==0)
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            else if(!(ch>=65 && ch<=90||ch>=97 && ch<=122||ch>=48 && ch<=57||ch=='/'||ch==8))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
        }
        else
        {
            char ch=evt.getKeyChar();
            if(evt.getKeyChar()==' ' && ser_tf.getCaretPosition()==0)
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            else if(!(ch>=65 && ch<=90||ch>=97 && ch<=122||ch==' '||ch==8))
            {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
        }
    }//GEN-LAST:event_ser_tfKeyTyped

    private void ser_bxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ser_bxActionPerformed
       if(ser_bx.getSelectedIndex()==1)
           url="select * from admission where reg_no =all(select reg_no from registration where upper(sname)=?)";
       else
           url="select * from admission where upper(reg_no)=?";
    }//GEN-LAST:event_ser_bxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void del_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btActionPerformed
        byte b=(byte) JOptionPane.showConfirmDialog(this, "Do you really want to delete this record?");
            if(b==0) 
        for (byte i = 0; i < table.getRowCount(); i++) {
            if(model.getValueAt(i, 6).equals(true)){
                try {
                    stmt=con.prepareStatement("delete from admission where  adm_no=?");
                    stmt.setString(1, model.getValueAt(i, 0).toString());
                    stmt.executeUpdate();
                    model.removeRow(i);
                    i--;
                    JOptionPane.showMessageDialog(this, "Record deleted successfully!");
                    backdata.backup("admission");
                    backdata.backup("automatic");
                } catch (SQLException ex) {
                    Logger.getLogger(CertificatePage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (WriteException ex) {
                    Logger.getLogger(AdmissionDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_del_btActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        for(byte i=0; i<table.getRowCount();i++){  
          if(model.getValueAt(i,6).equals(true)){
            table.addRowSelectionInterval(i,i);
            table.setSelectionBackground(Color.yellow);
            table.setSelectionForeground(Color.red); 
          }
          else
              table.removeRowSelectionInterval(i,i);  
    }
    }//GEN-LAST:event_tableMouseClicked

    private void disc_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disc_tfKeyReleased
        if(disc_tf.getText().length()!=0)
        tot_fee.setText(""+(Integer.parseInt(coufee_tf.getText())-Integer.parseInt(disc_tf.getText())));
    }//GEN-LAST:event_disc_tfKeyReleased

    private void up_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_btActionPerformed
        
    }//GEN-LAST:event_up_btActionPerformed
    public void fgcheck(JTextField c){
        String str=c.getText();
        if(str.equals("*Field is Mandatory")||str.equals("*Invalid Input")||str.isEmpty())
        {
            c.setText("");
            c.setBorder(new LineBorder(Color.BLACK));
            c.setForeground(Color.black);
        }
    }
    public void flcheck(JTextField c){
        String str=c.getText();
        if(str.length()==0)
        {
            c.setText("*Field is Mandatory");
            c.setForeground(Color.red);
            c.setBorder(new LineBorder(Color.RED));
        }
    }
    public void reset()
    {
        disc_tf.setText("");
        regno_tf.setText("");
        cou_tf.setText("");
        prev_tf.setText("");
        sname_tf.setText("");
        coufee_tf.setText("0");
        tot_fee.setText("");
        cou_box.setSelectedIndex(0);
        cou_box.setBorder(new LineBorder(Color.BLACK));
        regno_tf.requestFocus();
        regno_tf.setBorder(new LineBorder(Color.BLACK));
        regno_tf.setForeground(Color.black);
        disc_tf.setBorder(new LineBorder(Color.BLACK));
        disc_tf.setForeground(Color.black);
        cou_tf.setBorder(new LineBorder(Color.BLACK));
        cou_tf.setForeground(Color.black);
        cou_tf.setEditable(false);
        submit_bt.setEnabled(true);
        autogen();
    }
    public void check(){
        flcheck(regno_tf);
        flcheck(disc_tf);
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdmissionDetails().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdmissionDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cou_box;
    private javax.swing.JTextField cou_tf;
    private javax.swing.JTextField coufee_tf;
    private javax.swing.JLabel crapplying1;
    private javax.swing.JLabel crfee1;
    private javax.swing.JLabel crstudied1;
    private javax.swing.JButton del_bt;
    private javax.swing.JLabel disc1;
    private javax.swing.JTextField disc_tf;
    private javax.swing.JLabel doa1;
    private com.toedter.calendar.JDateChooser doa_date;
    private javax.swing.JLabel formno1;
    private javax.swing.JTextField formno_tf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField prev_tf;
    private javax.swing.JButton ref_bt;
    private javax.swing.JLabel regno1;
    private javax.swing.JTextField regno_tf;
    private javax.swing.JButton reset_bt;
    private javax.swing.JButton search_bt;
    private javax.swing.JComboBox<String> ser_bx;
    private org.jdesktop.swingx.JXSearchField ser_tf;
    private javax.swing.JLabel sname1;
    private javax.swing.JTextField sname_tf;
    private javax.swing.JButton submit_bt;
    private javax.swing.JScrollPane tab_pan;
    private javax.swing.JTable table;
    private javax.swing.JTextField tot_fee;
    private javax.swing.JLabel totfee1;
    private javax.swing.JButton up_bt;
    // End of variables declaration//GEN-END:variables
}
