
package raysproject;

import java.awt.Color;
import java.awt.Component;
import java.awt.MenuComponent;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import jxl.read.biff.BiffException;

/**
 *
 * @author Ravi Kishan
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setTitle("DashBoard");
        this.setLocationRelativeTo(null);
         
         Thread clock=new Thread(){
             @Override
             public void run(){
                 for(;;){
                    
                     try {
                          java.util.Date d=new java.util.Date();
                          lb.setText(DateFormat.getTimeInstance().format(d));
                          sleep(1000);
                     } catch (InterruptedException ex) {
                         Logger.getLogger(DashBordForm.class.getName()).log(Level.SEVERE, null, ex);
                     }
                 }
             }
         };
         clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        reg = new javax.swing.JPanel();
        reg_lb = new javax.swing.JLabel();
        cer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cou = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        branch = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        book = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        money = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cha_pswd = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rem = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        rec_cmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg.setBackground(new java.awt.Color(0, 102, 102));
        reg.setBorder(new javax.swing.border.MatteBorder(null));
        reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regMousePressed(evt);
            }
        });

        reg_lb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reg_lb.setForeground(new java.awt.Color(255, 255, 255));
        reg_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reg_lb.setText("Registration Form");

        javax.swing.GroupLayout regLayout = new javax.swing.GroupLayout(reg);
        reg.setLayout(regLayout);
        regLayout.setHorizontalGroup(
            regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reg_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );
        regLayout.setVerticalGroup(
            regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reg_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel1.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 80));

        cer.setBackground(new java.awt.Color(0, 102, 102));
        cer.setBorder(new javax.swing.border.MatteBorder(null));
        cer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Certificate");

        javax.swing.GroupLayout cerLayout = new javax.swing.GroupLayout(cer);
        cer.setLayout(cerLayout);
        cerLayout.setHorizontalGroup(
            cerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cerLayout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cerLayout.setVerticalGroup(
            cerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel1.add(cer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 80));

        cou.setBackground(new java.awt.Color(0, 102, 102));
        cou.setBorder(new javax.swing.border.MatteBorder(null));
        cou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                couMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                couMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Course");

        javax.swing.GroupLayout couLayout = new javax.swing.GroupLayout(cou);
        cou.setLayout(couLayout);
        couLayout.setHorizontalGroup(
            couLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, couLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        couLayout.setVerticalGroup(
            couLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel1.add(cou, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, 80));

        adm.setBackground(new java.awt.Color(0, 102, 102));
        adm.setBorder(new javax.swing.border.MatteBorder(null));
        adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admission Form");

        javax.swing.GroupLayout admLayout = new javax.swing.GroupLayout(adm);
        adm.setLayout(admLayout);
        admLayout.setHorizontalGroup(
            admLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        admLayout.setVerticalGroup(
            admLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel1.add(adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 80));

        branch.setBackground(new java.awt.Color(0, 102, 102));
        branch.setBorder(new javax.swing.border.MatteBorder(null));
        branch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                branchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                branchMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Branch");

        javax.swing.GroupLayout branchLayout = new javax.swing.GroupLayout(branch);
        branch.setLayout(branchLayout);
        branchLayout.setHorizontalGroup(
            branchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        branchLayout.setVerticalGroup(
            branchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, branchLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 250, 80));

        book.setBackground(new java.awt.Color(0, 102, 102));
        book.setBorder(new javax.swing.border.MatteBorder(null));
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Book");

        javax.swing.GroupLayout bookLayout = new javax.swing.GroupLayout(book);
        book.setLayout(bookLayout);
        bookLayout.setHorizontalGroup(
            bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookLayout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bookLayout.setVerticalGroup(
            bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel1.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 250, 80));

        money.setBackground(new java.awt.Color(0, 102, 102));
        money.setBorder(new javax.swing.border.MatteBorder(null));
        money.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moneyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moneyMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Money Receipt");

        javax.swing.GroupLayout moneyLayout = new javax.swing.GroupLayout(money);
        money.setLayout(moneyLayout);
        moneyLayout.setHorizontalGroup(
            moneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moneyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        moneyLayout.setVerticalGroup(
            moneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moneyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(money, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 230, 80));

        cha_pswd.setBackground(new java.awt.Color(0, 102, 102));
        cha_pswd.setBorder(new javax.swing.border.MatteBorder(null));
        cha_pswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cha_pswdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cha_pswdMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Change Password");

        javax.swing.GroupLayout cha_pswdLayout = new javax.swing.GroupLayout(cha_pswd);
        cha_pswd.setLayout(cha_pswdLayout);
        cha_pswdLayout.setHorizontalGroup(
            cha_pswdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cha_pswdLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cha_pswdLayout.setVerticalGroup(
            cha_pswdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel1.add(cha_pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 230, 80));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LogOut");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 40));

        rem.setBackground(new java.awt.Color(0, 102, 102));
        rem.setBorder(new javax.swing.border.MatteBorder(null));
        rem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                remMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                remMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Remainder");

        javax.swing.GroupLayout remLayout = new javax.swing.GroupLayout(rem);
        rem.setLayout(remLayout);
        remLayout.setHorizontalGroup(
            remLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remLayout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        remLayout.setVerticalGroup(
            remLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel1.add(rem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 80));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 950, 350));

        jPanel4.setBackground(new java.awt.Color(0, 109, 136));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DASHBOARD");

        lb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb.setBorder(new javax.swing.border.MatteBorder(null));

        rec_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select AnyOne for Recovery", "Registration", "Certificate", "Course", "Book_details", "signup", "state", "branch_details", "automatic", "admission", "money_receipt" }));
        rec_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rec_cmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(rec_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235)
                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(rec_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        kGradientPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rec_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rec_cmbActionPerformed
        try {
            if(rec_cmb.getSelectedIndex()!=0){
            Recovery.recmethod(rec_cmb.getSelectedItem().toString());
//            rec_cmb.remove((Component) rec_cmb.getSelectedItem());
            }
        } catch (IOException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rec_cmbActionPerformed

    private void regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseEntered
        // TODO add your handling code here:
       mouseEntered(reg);
    }//GEN-LAST:event_regMouseEntered

    private void regMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseExited
        mouseExited(reg);
    }//GEN-LAST:event_regMouseExited

    private void admMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseEntered
        mouseEntered(adm);
    }//GEN-LAST:event_admMouseEntered

    private void admMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admMouseExited
         mouseExited(adm);
    }//GEN-LAST:event_admMouseExited

    private void couMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_couMouseEntered
       mouseEntered(cou);
    }//GEN-LAST:event_couMouseEntered

    private void couMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_couMouseExited
        mouseExited(cou);
    }//GEN-LAST:event_couMouseExited

    private void cerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerMouseEntered
       mouseEntered(cer);
    }//GEN-LAST:event_cerMouseEntered

    private void cerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerMouseExited
        mouseExited(cer);
    }//GEN-LAST:event_cerMouseExited

    private void branchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchMouseEntered
        mouseEntered(branch);
    }//GEN-LAST:event_branchMouseEntered

    private void branchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchMouseExited
        mouseExited(branch);
    }//GEN-LAST:event_branchMouseExited

    private void moneyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyMouseEntered
       mouseEntered(money);
    }//GEN-LAST:event_moneyMouseEntered

    private void moneyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyMouseExited
       mouseExited(money);
    }//GEN-LAST:event_moneyMouseExited

    private void remMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remMouseEntered
         mouseEntered(rem);
    }//GEN-LAST:event_remMouseEntered

    private void remMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remMouseExited
        mouseExited(rem);
    }//GEN-LAST:event_remMouseExited

    private void bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseEntered
       mouseEntered(book);
    }//GEN-LAST:event_bookMouseEntered

    private void bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseExited
        mouseExited(book);
    }//GEN-LAST:event_bookMouseExited

    private void cha_pswdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cha_pswdMouseEntered
        mouseEntered(cha_pswd);
    }//GEN-LAST:event_cha_pswdMouseEntered

    private void cha_pswdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cha_pswdMouseExited
         mouseExited(cha_pswd);
    }//GEN-LAST:event_cha_pswdMouseExited

    private void regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_regMouseClicked

    private void regMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMousePressed
       System.out.println("hello");
    }//GEN-LAST:event_regMousePressed

    //mouse hover effect
    public void mouseEntered(JPanel men){
        men.setBackground(new Color(143,151,121));
    }
    public void mouseExited(JPanel mex){
        mex.setBackground(new Color(0,102,102));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adm;
    private javax.swing.JPanel book;
    private javax.swing.JPanel branch;
    private javax.swing.JPanel cer;
    private javax.swing.JPanel cha_pswd;
    private javax.swing.JPanel cou;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lb;
    private javax.swing.JPanel money;
    private javax.swing.JComboBox<String> rec_cmb;
    private javax.swing.JPanel reg;
    private javax.swing.JLabel reg_lb;
    private javax.swing.JPanel rem;
    // End of variables declaration//GEN-END:variables
}
