/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package raysproject;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;


public class RegistrationEntryForm extends javax.swing.JFrame {
    ButtonGroup bg;
    Connection con;
    PreparedStatement smt;
    ResultSet rs;
    int year,reg_no;
     ImageIcon img;
    String str;
     File f1,f2;
    public RegistrationEntryForm() throws SQLException {
        initComponents();
        //******************autogenerate for reg_no************************
        con=ConnDb.conLink();
        smt=con.prepareStatement("select reg_no from automatic");
        rs=smt.executeQuery();
        rs.next();
        reg_no=rs.getInt(1)+1;
        //+++++++++get current year of system++++++++++++++++
        Calendar cal=Calendar.getInstance();
         year = (cal.get(Calendar.YEAR))%100;
         autogen();
        ///**********************************************
        con_lb.setForeground(Color.red);
        this.setTitle("Registration- Entry Form");
        this.setLocationRelativeTo(null);
        Image icon=Toolkit.getDefaultToolkit().getImage("src\\icon\\raysnew.png");
        this.setIconImage(icon);
        dat.setDate(new java.sql.Date(System.currentTimeMillis()));
        nam_tf.requestFocus();
        blo_cb.setSelectedIndex(2);
        sta_cb.setSelectedIndex(0);
        bg=new ButtonGroup();
        mal_rb.setSelected(true);
        bg.add(mal_rb);
        bg.add(fem_rb);
        bg.add(bin_rb);
        this.getRootPane().setDefaultButton(sub_bt);
       redit.setVisible(false);
       dedit.setVisible(false);
    }
    void autogen(){
        boolean flag=true;
       if(reg_no<10)
           str="REPL/"+"BR01/"+year+"/R000"+reg_no;
       else if(reg_no<100)
           str="REPL"+"BR01"+year+"R00"+reg_no;
       else if(reg_no<1000)
           str="REPL"+"BR01"+year+"R0"+reg_no;
       else if(reg_no<10000)
           str="REPL"+"BR01"+year+"R"+reg_no;
       else{
           JOptionPane.showMessageDialog(null,"More than 9999 student not allowed");
           flag=false;
       }
       if(flag){
             reg_tf.setText(str); 
         }  
       else{
           sub_bt.setVisible(false);
       }
    }
    public void reset(){
        nam_tf.requestFocus();
        lb.setText("");
        con_lb.setText("");
        nam_tf.setText("");
        nam_tf.setForeground(Color.BLACK);
        fat_tf.setText("");
        fat_tf.setForeground(Color.BLACK);
        mot_tf.setText("");
        mot_tf.setForeground(Color.BLACK);
        dob.setDate(null);
        dob.setForeground(Color.BLACK);
        ema_tf.setText("");
        ema_tf.setForeground(Color.BLACK);
        con_tf.setText("");
        con_tf.setForeground(Color.BLACK);
        col_tf.setText("");
        col_tf.setForeground(Color.BLACK);
        per_ta.setText("");
        per_ta.setForeground(Color.BLACK);
        dis_tf.setText("");
        dis_tf.setForeground(Color.BLACK);
        nam_tf.setBorder(new LineBorder(Color.black));
        fat_tf.setBorder(new LineBorder(Color.black));
        mot_tf.setBorder(new LineBorder(Color.black));
        dob.setBorder(new LineBorder(Color.black));
        ema_tf.setBorder(new LineBorder(Color.black));
        con_tf.setBorder(new LineBorder(Color.black));
        col_tf.setBorder(new LineBorder(Color.black));
        per_ta.setBorder(new LineBorder(Color.black));
        dis_tf.setBorder(new LineBorder(Color.black));
        cor_ta.setText("");
        sta_cb.setSelectedIndex(0);
        blo_cb.setSelectedIndex(2);
        pro_cb.setSelectedIndex(0);
        pro_cb.setBorder(new LineBorder(Color.black));
        mal_rb.setSelected(true);
        ph.setIcon(null);
        aad_ph.setIcon(null);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        reg_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ph = new javax.swing.JLabel();
        mot_tf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nam_tf = new javax.swing.JTextField();
        fat_tf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        ema_tf = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        con_tf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        blo_cb = new javax.swing.JComboBox<>();
        pho_bt = new javax.swing.JButton();
        aad_bt = new javax.swing.JButton();
        bin_rb = new javax.swing.JRadioButton();
        fem_rb = new javax.swing.JRadioButton();
        mal_rb = new javax.swing.JRadioButton();
        gen_rb = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        col_tf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        per_ta = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        add_rb = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cor_ta = new javax.swing.JTextArea();
        aad_ph = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dis_tf = new javax.swing.JTextField();
        sta_cb = new javax.swing.JComboBox<>();
        sub_bt = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        pro_cb = new javax.swing.JComboBox<>();
        con_lb = new javax.swing.JLabel();
        dat = new com.toedter.calendar.JDateChooser();
        redit = new javax.swing.JCheckBox();
        dedit = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(49, 183, 194));
        kGradientPanel1.setkStartColor(new java.awt.Color(123, 195, 147));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(56, 78, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATION FORM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 980, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Date :");
        kGradientPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 57, 92, 24));

        reg_tf.setEditable(false);
        kGradientPanel1.add(reg_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 58, 217, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Registration No.");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 57, 107, 24));

        jPanel8.setBackground(new java.awt.Color(230, 230, 250));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ph.setBackground(new java.awt.Color(255, 51, 51));
        ph.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ph.setToolTipText("Attach your ");
        ph.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel8.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 103, 100));

        mot_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mot_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mot_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mot_tfFocusLost(evt);
            }
        });
        mot_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mot_tfKeyTyped(evt);
            }
        });
        jPanel8.add(mot_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 52, 241, 24));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Name");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 145, 24));

        nam_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nam_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nam_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nam_tfFocusLost(evt);
            }
        });
        nam_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nam_tfKeyTyped(evt);
            }
        });
        jPanel8.add(nam_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 22, 241, 24));

        fat_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fat_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fat_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fat_tfFocusLost(evt);
            }
        });
        fat_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fat_tfKeyTyped(evt);
            }
        });
        jPanel8.add(fat_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 197, 24));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Father's Name");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 106, 24));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Mother's Name");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 145, 24));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("D.O.B");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 106, 24));

        dob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dobFocusLost(evt);
            }
        });
        jPanel8.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 198, -1));

        ema_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ema_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ema_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ema_tfFocusLost(evt);
            }
        });
        ema_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ema_tfKeyTyped(evt);
            }
        });
        jPanel8.add(ema_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 241, 24));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Email Id");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 145, 22));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Contact No.");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 106, 22));

        con_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        con_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                con_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                con_tfFocusLost(evt);
            }
        });
        con_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                con_tfKeyTyped(evt);
            }
        });
        jPanel8.add(con_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 198, 24));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Program");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 145, 22));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Blood Group");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 95, 22));

        blo_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A","B","AB","O","A-","B-","AB-","O-"}));
        jPanel8.add(blo_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 198, -1));

        pho_bt.setBackground(new java.awt.Color(0, 116, 226));
        pho_bt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pho_bt.setForeground(new java.awt.Color(255, 255, 255));
        pho_bt.setText("UPLOAD");
        pho_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pho_btActionPerformed(evt);
            }
        });
        jPanel8.add(pho_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 103, -1));

        aad_bt.setBackground(new java.awt.Color(0, 116, 226));
        aad_bt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aad_bt.setForeground(new java.awt.Color(255, 255, 255));
        aad_bt.setText("UPLOAD");
        aad_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aad_btActionPerformed(evt);
            }
        });
        jPanel8.add(aad_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        bin_rb.setBackground(new java.awt.Color(230, 230, 250));
        bin_rb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bin_rb.setText("Binary");
        jPanel8.add(bin_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 73, -1));

        fem_rb.setBackground(new java.awt.Color(230, 230, 250));
        fem_rb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fem_rb.setText("Female");
        jPanel8.add(fem_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 71, -1));

        mal_rb.setBackground(new java.awt.Color(230, 230, 250));
        mal_rb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mal_rb.setText("Male");
        jPanel8.add(mal_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 60, -1));

        gen_rb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gen_rb.setText("Gender");
        jPanel8.add(gen_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 56, 22));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("College Name");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 137, 22));

        col_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        col_tf.setNextFocusableComponent(per_ta);
        col_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                col_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                col_tfFocusLost(evt);
            }
        });
        col_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                col_tfKeyTyped(evt);
            }
        });
        jPanel8.add(col_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 241, 24));

        per_ta.setColumns(20);
        per_ta.setLineWrap(true);
        per_ta.setRows(5);
        per_ta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                per_taFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                per_taFocusLost(evt);
            }
        });
        per_ta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                per_taKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(per_ta);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 241, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Permanent address");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 131, 22));

        add_rb.setBackground(new java.awt.Color(230, 230, 250));
        add_rb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_rb.setText("click (if permanent address is same as corresponding address)");
        add_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_rbActionPerformed(evt);
            }
        });
        jPanel8.add(add_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 388, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Correspondance address");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 116, 226));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 692, 101, -1));

        jButton4.setBackground(new java.awt.Color(204, 0, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 692, 101, -1));

        cor_ta.setColumns(20);
        cor_ta.setLineWrap(true);
        cor_ta.setRows(5);
        cor_ta.setWrapStyleWord(true);
        cor_ta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cor_taKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(cor_ta);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 244, -1));

        aad_ph.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aad_ph.setText("aadhar card");
        aad_ph.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel8.add(aad_ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 330, 151));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("District");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 78, 25));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("State");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 78, 25));

        dis_tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dis_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dis_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dis_tfFocusLost(evt);
            }
        });
        dis_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dis_tfKeyTyped(evt);
            }
        });
        jPanel8.add(dis_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 198, 24));

        sta_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Bihar","Andhra Pradesh","Arunachal Pradesh","Assam","Chhattisgarh","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu & Kashmir","Jharkhand","Karnataka","Kerala","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Tripura","Telangana","Uttar Pradesh","Uttarakhand","West Bengal","Andaman & Nicobar","Chandigarh","Dadra & Nagar Haveli","Daman & Diu","Lakshadweep","Puducherry"}));
        jPanel8.add(sta_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 198, -1));

        sub_bt.setBackground(new java.awt.Color(0, 116, 226));
        sub_bt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sub_bt.setForeground(new java.awt.Color(255, 255, 255));
        sub_bt.setText("SUBMIT");
        sub_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btActionPerformed(evt);
            }
        });
        jPanel8.add(sub_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        reset.setBackground(new java.awt.Color(204, 0, 51));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel8.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 80, -1));
        jPanel8.add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 116, 240, 10));
        jPanel8.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 116, 240, 10));

        pro_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose anyOne","Item 1", "Item 2", "Item 3", "Item 4" }));
        pro_cb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pro_cbFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pro_cbFocusLost(evt);
            }
        });
        jPanel8.add(pro_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, -1));
        jPanel8.add(con_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 200, -1));

        kGradientPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 935, 480));

        dat.setEnabled(false);
        dat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                datFocusLost(evt);
            }
        });
        kGradientPanel1.add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 198, -1));

        redit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        redit.setText("Edit");
        redit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reditActionPerformed(evt);
            }
        });
        kGradientPanel1.add(redit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 60, -1));

        dedit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dedit.setText("Edit");
        dedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deditActionPerformed(evt);
            }
        });
        kGradientPanel1.add(dedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 50, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_rbActionPerformed
            
        if(add_rb.isSelected() ){
            cor_ta.setEditable(false);
            if( per_ta.getText().length()>0&& per_ta.getText().equals("*Field is mandatory!")  ){
              
              cor_ta.setText(""+per_ta.getText().trim());  
            }
    }
    else {
           cor_ta.setEditable(true);
           cor_ta.setText("");
        }
       
    }//GEN-LAST:event_add_rbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        reset();
        
    }//GEN-LAST:event_resetActionPerformed

    private void nam_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nam_tfFocusLost
       regfl(nam_tf);
    }//GEN-LAST:event_nam_tfFocusLost

    private void nam_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nam_tfFocusGained
        regfg(nam_tf);
       
    }//GEN-LAST:event_nam_tfFocusGained

    private void nam_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nam_tfKeyTyped
        regkt(evt,nam_tf);
    }//GEN-LAST:event_nam_tfKeyTyped

    private void fat_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fat_tfFocusLost
         regfl(fat_tf);
    }//GEN-LAST:event_fat_tfFocusLost

    private void fat_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fat_tfFocusGained
    regfg(fat_tf);
    }//GEN-LAST:event_fat_tfFocusGained

    private void fat_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fat_tfKeyTyped
        regkt(evt,fat_tf);
    }//GEN-LAST:event_fat_tfKeyTyped

    private void mot_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mot_tfFocusLost
        regfl(mot_tf);
    }//GEN-LAST:event_mot_tfFocusLost

    private void mot_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mot_tfFocusGained
        // TODO add your handling code here:
       regfg(mot_tf);
    }//GEN-LAST:event_mot_tfFocusGained

    private void mot_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mot_tfKeyTyped
        // TODO add your handling code here:

    regkt(evt,mot_tf);
    }//GEN-LAST:event_mot_tfKeyTyped

    private void dobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobFocusLost
        // TODO add your handling code here
        Date str=dob.getDate();
       if(str.equals(null)) {
           dob.setBorder(BorderFactory.createLineBorder(Color.red));
      //  dob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
          Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_dobFocusLost

    private void ema_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ema_tfKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if((evt.getKeyChar()==' ')&& dis_tf.getCaretPosition()==0)
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
         else if(!(ch>=65&& ch<=90 || ch>=97 && ch<=122 || ch=='@'||ch=='.'))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_ema_tfKeyTyped

    private void con_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_con_tfFocusLost
        regfl(con_tf);
        
    }//GEN-LAST:event_con_tfFocusLost

    private void con_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_con_tfKeyTyped
         
        char ch=evt.getKeyChar();
         if(con_tf.getText().length()>=10)
         {
             evt.consume();
             Toolkit.getDefaultToolkit().beep();
         }
         else if(!(ch>='0'&& ch<='9'|| ch==8))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_con_tfKeyTyped

    private void con_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_con_tfFocusGained
        // TODO add your handling code here:
        regfg(con_tf);
    }//GEN-LAST:event_con_tfFocusGained

    private void col_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_col_tfFocusLost
        // TODO add your handling code here:

        regfl(col_tf);
    }//GEN-LAST:event_col_tfFocusLost

    private void col_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_col_tfFocusGained
        regfg(col_tf);
    }//GEN-LAST:event_col_tfFocusGained

    private void col_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_col_tfKeyTyped
        regkt(evt,col_tf);
    }//GEN-LAST:event_col_tfKeyTyped

    private void per_taFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_per_taFocusLost
        // TODO add your handling code here:
        String str=per_ta.getText();
        if(str.trim().length()==0)
        {
            per_ta.setForeground(Color.red);
            per_ta.setText("*Field is mandatory!");
            per_ta.setBorder(new LineBorder(Color.red));
            Toolkit.getDefaultToolkit().beep();
        }
      //  regfl(per_ta);
    }//GEN-LAST:event_per_taFocusLost

    private void per_taFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_per_taFocusGained
        // TODO add your handling code here:
          String str=per_ta.getText();
        if(str.equals("*Field is mandatory!"))
        {
            per_ta.setForeground(Color.black);
            per_ta.setText("");
            per_ta.setBorder(new LineBorder(Color.black));
        }
    
            
    }//GEN-LAST:event_per_taFocusGained

    private void dis_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dis_tfFocusLost
        regfl(dis_tf);
    }//GEN-LAST:event_dis_tfFocusLost

    private void dis_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dis_tfFocusGained
        // TODO add your handling code here:
        regfg(dis_tf);
    }//GEN-LAST:event_dis_tfFocusGained

    private void dis_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dis_tfKeyTyped
    regkt(evt,dis_tf);
    }//GEN-LAST:event_dis_tfKeyTyped

    private void per_taKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_per_taKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if((evt.getKeyChar()==' '||evt.getKeyChar()=='.'||evt.getKeyChar()==9) && per_ta.getCaretPosition()==0)
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_per_taKeyTyped

    private void cor_taKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cor_taKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
         if(!(ch>=65&& ch<=90 || ch>=97 && ch<=122 || ch==' '||ch=='.'||ch==8))
        {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_cor_taKeyTyped

    private void ema_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ema_tfFocusLost
        // TODO add your handling code here:
        lb.setForeground(Color.red);
        
        String str = ema_tf.getText();

if (str.length()>0)
{
    if (str.endsWith(".in") || str.endsWith(".com"))
    {
        if(str.contains("@"))
        {
            byte index1=(byte) str.indexOf("@");
            byte index2=(byte) str.indexOf(".");
            if (index2==(index1+1))
            {
                ema_tf.setBorder(new LineBorder(Color.red));
                Toolkit.getDefaultToolkit().beep();
                lb.setText("*Please enter a valid email Id!");
            }
            else 
                lb.setText("");
             
        }
        else
        {
            ema_tf.setBorder(new LineBorder(Color.red));
            Toolkit.getDefaultToolkit().beep();
            lb.setText("*Please enter a valid email Id!");
        }     
    }
    else{
            ema_tf.setBorder(new LineBorder(Color.red));
            Toolkit.getDefaultToolkit().beep();
            lb.setText("*Please enter a valid email Id!");
        }   
}
else
    lb.setText("");  
    }//GEN-LAST:event_ema_tfFocusLost

    private void ema_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ema_tfFocusGained
        // TODO add your handling code here:
        ema_tf.setBorder(new LineBorder(Color.black));
        lb.setText("");
    }//GEN-LAST:event_ema_tfFocusGained

    private void pho_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pho_btActionPerformed
        // TODO add your handling code here:
          JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(this);
        f1 = ch.getSelectedFile();
        img=new ImageIcon(new ImageIcon(""+f1).getImage().getScaledInstance(ph.getWidth(), ph.getHeight(),Image.SCALE_SMOOTH));
        ph.setIcon(img);
    }//GEN-LAST:event_pho_btActionPerformed

    private void aad_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aad_btActionPerformed
        // TODO add your handling code here:
          JFileChooser ch=new JFileChooser();
        ch.showOpenDialog(this);
        f2 = ch.getSelectedFile();
        ImageIcon img=new ImageIcon(new ImageIcon(""+f2).getImage().getScaledInstance(ph.getWidth(), ph.getHeight(),Image.SCALE_DEFAULT));
        aad_ph.setIcon(img);
    }//GEN-LAST:event_aad_btActionPerformed

    private void pro_cbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pro_cbFocusLost
        // TODO add your handling code here:
         if(pro_cb.getSelectedIndex()==0) {
            pro_cb.setBorder(new LineBorder(Color.red));
        }
    }//GEN-LAST:event_pro_cbFocusLost

    private void pro_cbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pro_cbFocusGained
        // TODO add your handling code here:
          pro_cb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        //pro_cb.setBorder(new LineBorder(Color.BLACK));
    }//GEN-LAST:event_pro_cbFocusGained

    private void datFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datFocusLost
        // TODO add your handling code here:
        boolean dt=dat.getDateFormatString().equals("DD/MM/YYY");
        if(dt)
            dat.setBorder(BorderFactory.createBevelBorder(4));
    }//GEN-LAST:event_datFocusLost

    private void reditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reditActionPerformed
        // TODO add your handling code here:
           if(dedit.isSelected()){
            reg_tf.setEditable(true);
        }
        else 
            reg_tf.setEditable(false);
    }//GEN-LAST:event_reditActionPerformed

    private void deditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deditActionPerformed
        // TODO add your handling code here:
        if (dedit.isSelected()) {
            dat.setEnabled(true);
        }
        else
            dat.setEnabled(false);
    }//GEN-LAST:event_deditActionPerformed

    private void sub_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btActionPerformed
        try {
            String gen;
            smt=con.prepareStatement("insert into registration values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            smt.setString(1, reg_tf.getText());
            Calendar c=dat.getCalendar();
            String dt=""+c.get(Calendar.DATE)+"-"+(c.get(Calendar.MONTH)+1)+"-"+c.get(Calendar.YEAR);
            smt.setString(2, dt);
            smt.setString(3, nam_tf.getText());
            smt.setString(4, fat_tf.getText());
            smt.setString(5, mot_tf.getText());
            Calendar d=dob.getCalendar();
            String dtt=d.get(Calendar.DATE)+"-"+(d.get(Calendar.MONTH)+1)+"-"+d.get(Calendar.YEAR);
            smt.setString(6,dtt);
            smt.setString(7, ema_tf.getText());
            smt.setString(8,con_tf.getText());
            smt.setString(9, ""+pro_cb.getSelectedItem());
            smt.setString(10,""+ blo_cb.getSelectedItem());
            smt.setString(11, col_tf.getText());
            if(mal_rb.isSelected())
                    gen="Male";
            else if(fem_rb.isSelected())
                    gen="Female";
            else
                    gen="Binary";
            smt.setString(12,gen);
            smt.setString(13, per_ta.getText());
            smt.setString(14, dis_tf.getText());
            smt.setString(15, ""+sta_cb.getSelectedItem());
            FileInputStream fin=new FileInputStream(f1);
            smt.setBinaryStream(16,fin,fin.available());
            fin=new FileInputStream(f2);
            smt.setBinaryStream(17,fin,fin.available());
            smt.setString(18, cor_ta.getText());
            smt.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Inserted Successfully!");
            reg_no++;
            autogen();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Something went Wrong!");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RegistrationEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RegistrationEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sub_btActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            smt=con.prepareStatement("update automatic set reg_no=?");
            smt.setInt(1, reg_no-1);
            smt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationEntryForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    //public void regkt()
    public void regfg(JTextField fg){
          String str=fg.getText();
        if(str.equals("*Field is mandatory!"))
        {
            fg.setForeground(Color.black);
            fg.setText("");
            fg.setBorder(new LineBorder(Color.black));
        }
        else if(fg.equals(con_tf)){
             con_tf.setBorder(new LineBorder(Color.black));
             con_lb.setText("");
        }
       
    }
    public void regfl(JTextField fl){
        String str=fl.getText();
        if(str.length()==0)
        {
            fl.setForeground(Color.red);
            fl.setText("*Field is mandatory!");
            fl.setBorder(new LineBorder(Color.red));
            Toolkit.getDefaultToolkit().beep();
        }
        else if(fl.equals(con_tf)){
            if(str.length()<10){
             con_lb.setText("*contact no. must be 10 digits!");
             con_tf.setBorder(new LineBorder(Color.red));
            }
            else
              // con_tf.setBorder(new LineBorder(Color.black)); 
                con_lb.setText("");
            
               
        }
    }
    public void regkt(KeyEvent e,JTextField c)
    {
        char ch=e.getKeyChar();
        if((e.getKeyChar()==' '||e.getKeyChar()=='.')&& c.getCaretPosition()==0)
        {
            e.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        else if(!(ch>=65&& ch<=90 || ch>=97 && ch<=122 || ch==' '||ch=='.'||ch==8))
        {
            e.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegistrationEntryForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(RegistrationEntryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aad_bt;
    private javax.swing.JLabel aad_ph;
    private javax.swing.JRadioButton add_rb;
    private javax.swing.JRadioButton bin_rb;
    private javax.swing.JComboBox<String> blo_cb;
    private javax.swing.JTextField col_tf;
    private javax.swing.JLabel con_lb;
    private javax.swing.JTextField con_tf;
    private javax.swing.JTextArea cor_ta;
    private com.toedter.calendar.JDateChooser dat;
    private javax.swing.JCheckBox dedit;
    private javax.swing.JTextField dis_tf;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField ema_tf;
    private javax.swing.JTextField fat_tf;
    private javax.swing.JRadioButton fem_rb;
    private javax.swing.JLabel gen_rb;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JRadioButton mal_rb;
    private javax.swing.JTextField mot_tf;
    private javax.swing.JTextField nam_tf;
    private javax.swing.JTextArea per_ta;
    private javax.swing.JLabel ph;
    private javax.swing.JButton pho_bt;
    private javax.swing.JComboBox<String> pro_cb;
    private javax.swing.JCheckBox redit;
    private javax.swing.JTextField reg_tf;
    private javax.swing.JButton reset;
    private javax.swing.JComboBox<String> sta_cb;
    private javax.swing.JButton sub_bt;
    // End of variables declaration//GEN-END:variables
}
